version: "3"
networks:
  banco:
    driver: bridge
  banconosql:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge
services:
  db:
    image: postgres:10.10-alpine
    container_name: "postgreSQL"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "knownledge"
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 54320:5432
    networks:
      - banco
  banconosql:
    image: mvertes/alpine-mongo:latest
    restart: always
    container_name: "mongodb"
    environment:
      MONGO_INITDB_DATABASE: "knowledge_stats"
    ports:
      - 27017:27017
    networks:
      - banconosql
  frontend:
    image: frontend:latest
    container_name: "web"
    volumes:
      - ./frontend:/app
    # command: sh -c "cd /frontend && npm i && npm run serve"
    ports:
      - 80:8080
    networks:
      - frontend
    depends_on:
      - backend
  backend:
    image: backend:latest
    container_name: "aplicacao"
    volumes:
      - . .
      # Scripts instalar knex e rodar migrations
      # - ./backend/scripts/knex.sh:/scripts
    # working_dir: /backend
    ports:
      - 3000:3000
    # command: sh -c "cd /backend && npm i && npm i -g knex && knex migration:latest && npm start"
    # command: bash -C 'knex.sh'
    networks:
      - backend
      - banco
      - banconosql
      - frontend
    depends_on:
      - db
      - banconosql
    links:
      - db
      - banconosql
